name: Generate Snake

on:
  # A cada vez que o usuário fizer "push" ou "pull_request", o workflow será acionado
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Também agenda a execução a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura e gera o arquivo SVG com a cobra
      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: robertoamato # Altere aqui para o seu nome de usuário do GitHub
          outputs: "github-contribution-grid-snake.svg"

      # Faz commit e push do arquivo gerado
      - name: Push Snake grid to repository
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generate Snake animation"
          git push
